version: '3'

services:
  esc-identifier-postgres:
    image: postgres:9.6
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data
      - ./data:/opt/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgresql/data
    ports:
      - 5432:5432

  mongo:
    image: mongo:3.4
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - 27017:27017

  esc-identifier:
    build: ./esc_identifier
    image: local/esc-identifier:latest
    volumes:
      - ./esc_identifier:/opt/esc_identifier
      - ./data:/opt/data
    environment:
      - DB_URI=postgresql://root:secret@esc-identifier-postgres:5432/esc
      - KDD_DB_URI=postgresql://root:secret@esc-identifier-postgres:5432/Kdd2013AuthorPaperIdentification
      - MONGO_URI=mongodb://mongo:27017/
    command:
      - python3.6
      - manage.py
      - show_kdd_authors