version: '3'

services:
  esc-identifier-postgres:
    image: postgres:9.6
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgresql/data
    ports:
      - 5432:5432

  esc-identifier:
    build: ./esc_identifier
    image: local/esc-identifier:latest
    volumes:
      - ./esc_identifier:/opt/esc_identifier
      - ./data:/opt/data:ro
    environment:
      - DB_URI=postgresql://root:secret@esc-identifier-postgres:5432
    command:
      - python3.6
      - -m
      - "esc_identifier.mirna_parser"
      - --drop-db
      - /opt/data/pubmed_mirna_results.txt
